[package]
name = "tools"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
rayon = "1.0.3"
crossbeam = "0.7.1"
bozorth = { path = "../bozorth" }
isoparser = { path = "../isoparser" }
anyhow = "1.0.28"
time = "0.2.12"
argh = "0.1.3"
structopt = "0.3.16"
